export const doctorSpecialization = [
    "Allergist/Immunologist",
    "Anesthesiologist",
    "Cardiologist",
    "Colon and Rectal Surgeon",
    "Critical Care Medicine Specialist",
    "Dermatologist",
    "Endocrinologist",
    "Emergency Medicine Specialist",
    "Family Medicine Physician",
    "Gastroenterologist",
    "Geriatric Medicine Specialist",
    "Hematologist",
    "Hospice and Palliative Medicine Specialist",
    "Infectious Disease Specialist",
    "Internist",
    "Medical Geneticist",
    "Nephrologist",
    "Neurologist",
    "Neurosurgeon",
    "Obstetrician/Gynecologist (OB/GYN)",
    "Oncologist",
    "Ophthalmologist",
    "Orthopedic Surgeon",
    "Otolaryngologist (ENT)",
    "Pathologist",
    "Pediatrician",
    "Physiatrist",
    "Plastic Surgeon",
    "Psychiatrist",
    "Pulmonologist",
    "Radiologist",
    "Rheumatologist",
    "Sleep Medicine Specialist",
    "Sports Medicine Specialist",
    "Surgeon",
    "Thoracic Surgeon",
    "Urologist",
    "Vascular Surgeon"
]